---
- name: query a bastion host for facts
  hosts: tag_three_tier_app_{{ GUID }}_bastion
  gather_facts: false
  become: false
  vars:
    ansible_user: ec2-user

  tasks:

  - name: gather facts with setup
    setup:
    register: myfacts  

  - name: output the facts
    debug:
      msg: "{{ myfacts }}"

